#!/bin/bash

# Check if at least one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain/organisation name>"
    exit 1
fi

domain="$1"

curl -s https://crt.sh/\?q\=$domain\&output\=json | jq . | grep common_name | cut -d ":" -f2 | tr -d '",' > "$domain.domains.txt"
